# Generated by Django 3.2.16 on 2022-11-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('dni_empleado', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, max_length=30, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('genero', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_tienda', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'empleados2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_venta', models.IntegerField(blank=True, null=True)),
                ('precio_costo', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroClienteTienda',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=15)),
                ('dni_cli', models.IntegerField()),
                ('nombres_cli', models.CharField(max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True)),
                ('distrito', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'registro_cliente_tienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=45, null=True)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=45)),
                ('nombre_dueño', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_alquiler', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCategorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleados',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=40, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('distrito', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('monto_total', models.FloatField(blank=True, null=True)),
                ('nombres_cli', models.CharField(blank=True, max_length=30, null=True)),
                ('dni_cli', models.IntegerField(blank=True, null=True)),
                ('tipo_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_boleta', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('igb', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_tienda', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
